### PR TITLE
added form data type in post and put request type, to support different content-type in future

### PR DESCRIPTION
**Pull request by Sagar2011**
@jackfranklin can you please review changes

### CODE REVIEW

**Comment by Sagar2011** [comment]
@jackfranklin Can you please merge this request as soon as possible?

**Comment by jackfranklin** [comment]
@Sagar2011 thanks for this PR. This repo isn't one that I have any desire to maintain any more. If you wanted to maintain it I'm happy to transfer the repo + the npm name to you, or give you contributing rights on github. What do you think?

**Comment by Sagar2011** [comment]
@jackfranklin I am happy to take that mantle. Please do the needful.

**Comment by Sagar2011** [comment]
@jackfranklin can you also let me know the npm, so I can start maintaining that part as well.

**Comment by jackfranklin** [comment]
Sorry for my slow reply. For now feel free to ping me (on GitHub, or email jack at jackfranklin dot net directly) when you'd like a new release published and I can do that :+1:

**Pull request merged**
