### PR TITLE
fix: Added more options to the IFetchOptions interface

### PR DESCRIPTION
**Pull request by arunrreddy**
Added the standard options which are present on the fetch API standard. The current options allow editing the headers of the request. I have added options to the IFetchOptions interface to accept all valid options present in a standard fetch API request

### CODE REVIEW

**Comment by arunrreddy** [comment]
Can you please merge this request as soon as possible?

**Comment by jackfranklin** [comment]
@arunrreddy thanks for this and sorry for my silence. I don't want to include the package-lock, as I default to yarn, so if you could update this PR with just the code changes then I'll be happy to merge and ship the new verson

**Comment by arunrreddy** [comment]
@jackfranklin Updated code as per your request.

**Comment by jackfranklin** [comment]
@arunrreddy out as 0.4.2. Thank you!

**Comment by arunrreddy** [comment]
Thanks a lot!

**Pull request merged**
